import Head from 'next/head'
import PageLink from '../../components/pageLink'

// 問題1: CSS modulesになるようファイルを編集してください
import './sample.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>react-css - CSS Modules</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLink current="CSS Modules" />

      {/* 問題2: sample.module.scssの.problem2を適用してください */}
      <p>問題2</p>

      {/* 問題3: sample.module.scssの.problem3_1, problem3_2を適用してください */}
      <p>問題3</p>

      {/* 問題4: sample.module.scssの.problem4を適用してください */}
      <p>問題4</p>

      {/* 問題5: sample.module.scssの.problem5を適用してください */}
      <p>問題5</p>
    </>
  )
}

