import Head from 'next/head'
import PageLink from '../components/pageLink';

export default function Home() {
  return (
    <>
      <Head>
        <title>react-css - Top Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLink current="Top" />
      <p>上のリンクから好きなページに移ってください</p>
    </>
  );
}

